#!/bin/bash
if [ "$1" == "" ] 
then
	echo "Input project name:"
	read projectName
else 
	projectName=$1
fi

repositoryFolder=/var/git/
projectFolder=$repositoryFolder$projectName

if [ "$projectFolder" == "$repositoryFolder" ] 
then
	echo "ERROR. Repository name is empty"
	exit 0
fi

#creating directory for project in git folder
test -d $projectFolder || mkdir $projectFolder
git init --bare --shared=group $projectFolder

echo "Name of developer in system:"
read developerName

#echo "Input new group:"
group="p_${projectName}"
#read group
groupadd $group

usermod -aG $group $developerName
usermod -aG $group html 
#usermod -aG $group qa

#echo "Fill username:group:"
#read rights

cp /home/nestor/git-hook/pre-receive.sh ${projectFolder}hooks/pre-receive
chown -R $developerName:$group $projectFolder
chmod -R 775 $projectFolder

#echo $projectFolder

